### ISSUE TITLE
codesign requires Xcode Command Line Tools!

### ISSUE THREAD

**Issue by PMheart** [syscl/HiDPI-RecoveryHD#1]
Hi, syscl:
I saw your script and I found that your script runs codesign. Nevertheless, codesign requires CLT. So for most normal users who didn't install CLT, the patch will not work. What's more, perl will work without codesign. This may cause a problem -- will got KP! My app also requires codesign for MBR patch. And have no idea with this...

**Comment by PMheart** [comment]
Oops. BTW and for 10.12.x the perl code changed. i.e. You cannot use this perl patch for 10.12.x's IOKit binary... The new way has not been found currently.

**Comment by syscl** [comment]
Thks for your kindly post, I had soon known that problem(and the solution) at the time when  macOS DP1 was released, but I'm still busy making kext these days, so I have got not time to update script ASAP.

syscl

**Comment by syscl** [comment]
Fix up issue credit syscl.

syscl
